

pathes:
    ROOT_PATH: '/mnt/samba/Daten/Projekte/Raspberry/ESPWeb/'
    DATA: 'data/'                 # not used yet
    LOG: 'log/'
    RRD: 'rrd/'
    YML: 'yml/'
    PIC: 'pic/'
    ARCH: 'archiv/'
    SCENE: 'Scenes/'
    PROG: 'prog/'
    HTML: 'html/'
    IPAdr: 'IPAdr'

Communication:
    ServerName: '192.168.1.53'    
    ServerPort: 8080
    
files:
    LOG: 'ServESP.log'
    DATASTORE_YML: 'datastore.yml'

suffixes:
    log: # '-%Y_%m_%d__%H-%M-%S'     #date and time
         '-%Y_%m_%d'                #date only
         #''                         # hostname only
    data: '-%Y_%m_%d__%H-%M-%S'     #date and time
          #'-%Y_%m_%d'               #date only
          #''                        #without date and time

debug:
    datefmt: '%d.%m.%Y %H:%M:%S'      # normal
    #datefmt: '%d.%m.%Y %H:%M:%S.%s'   # fine (with ms)
    hirestime: False                    # time resolution in data logs (true=ms, false=s)
    logYML: True                      #put the yml-file into the log
    verbose: True

devices:
    Schnell_AC_0B_FB_D6_41_74: with_RRD_and_CONF
    Langsam_CC_50_E3_3C_17_68: without_RRD_and_CONF
    
archive:
    weather.log: 7
    Makegraphics.log: 2
    dbupload.log: 2
    ServESP.log: 8
    ChangedIPs.log: 6
    cs.log: 5
    DevView.log: 4
    cnt_not_0.lox: 7
    cnt.log: 7
    Garden.log: 7
    