
primary:
    can:
        car: can1
    tls:
        path_to_own_cert: "/home/bplus/primaerseite/certs/"
        path_to_public_certs: "/home/bplus/primaerseite/shared_files/certs_public/"
    network:
        autobind: False
    location: "stamme_2.yml"
    DATASTORE_YML: "/home/bplus/primaerseite/shared_files/datastore.yml"
    CAN_dbc: "primary.dbc"
    powermeter:
        ip: '192.168.2.253'
        username: 'admin'
        password: 'admin'
    WEB:
        BASE_URL: 'http://192.168.2.59:8080'
        infos:
            - ["IP", ": ", ["System", "own_IP", "CURRENT_DATA"]]
            - ["Disk usage ", "[%]: ", ['disk_usage', 'percent', 'CURRENT_DATA']]
            - ["Power usage ", "[kWh]: ", ["powermeter", "E(P)in", 'CURRENT_DATA']]
            - ["Power ", "[kW]: ", ["powermeter", "P_total", 'CURRENT_DATA']]
            - ["System uptime ", "[s]: ", ["System", "uptime_sys", 'CURRENT_DATA']]
            - ["App uptime ", "[s]: ", ["System", "uptime_app", 'CURRENT_DATA']]

secondary:
    can:
        car: can1
        antenna: can0
    server:
        port1: 9003
        hostname_list:
            - "primary4c52629f697c"
            - "primary0030591540e0"
            - "primary00305914880b"
    tls:
        path_to_own_cert: "/home/bplus/sekundaerseite/certs/"
        path_to_public_certs: "/home/bplus/sekundaerseite/shared_files/certs_public/"
    network:
        autobind: False
        NetPrefix: "wlp"
        Hostprefix: "00:0e:8e:93:af:72"
        WiFiDelay: 0.5
    GUI:
        display_orientation: "right"
        WPT_Button: True
        kill_Button: True
        dummy_machine: False
        infos:
            # infos displayed in the info tab
            # syntax: [name, datatype, [datastore location]]
            - ["MyName", "str", ["System", "MyName", "CURRENT_DATA"]]
            - ["own IP", "str", ["System", "own_IP", "CURRENT_DATA"]]
            - ["connected to", "str", ["System", "ServerName", "CURRENT_DATA"]]
            - ["connected IP", "str", ["System", "Server_IP", "CURRENT_DATA"]]
            - ["", "", ["InfoTab", "divider", "STORE_MODE_DATA"]]
            - ['x_10::current_in_range', 'bool', ['Ant_X_10', 'x_pos', 'CURRENT_IN_RANGE']]
            - ['y_11::current_in_range', 'bool', ['Ant_Y_11', 'y_pos', 'CURRENT_IN_RANGE']]
            - ['x_10::x_pos', 'int', ['Ant_X_10', 'x_pos', 'CURRENT_DATA']]
            - ['y_11::y_pos', 'int', ['Ant_Y_11', 'y_pos', 'CURRENT_DATA']]
            - ["Transponder", "RFID #", ["Ant_X_10", "x_Transponder", "CURRENT_DATA"]]
            - ["", "", ["InfoTab", "divider", "STORE_MODE_DATA"]]
            - ['is charging', 'bool', ['EDAG1', 'Vehicle_is_charging', 'CURRENT_DATA']]
            - ['Voltage', '[V]', ['EDAG1', 'Bus_Voltage', 'STORE_MODE_DATA']]
            - ['Current', '[A]', ['EDAG1', 'Bus_Current', 'STORE_MODE_DATA']]
            - ['disc', '%', ['disk_usage', 'percent', 'CURRENT_DATA']]
    WEB:
        BASE_URL: 'http://192.168.2.59:8080'
        infos:
            - ["IP", ": ", ["System", "own_IP", "CURRENT_DATA"]]
            - ["Disk usage ", "[%]: ", ['disk_usage', 'percent', 'CURRENT_DATA']]
            - ["EDAG Busv. ", "[V]: ", ['EDAG1', 'Bus_Voltage', 'STORE_MODE_DATA']]
            - ["charging", ": ", ['EDAG1', 'Vehicle_is_charging', 'CURRENT_DATA']]
            - ["System uptime ", "[s]: ", ["System", "uptime_sys", 'CURRENT_DATA']]
            - ["App uptime ", "[s]: ", ["System", "uptime_app", 'CURRENT_DATA']]

    DATASTORE_YML: "/home/bplus/sekundaerseite/shared_files/datastore.yml"
    CAN_dbc: "secondary.dbc"


pathes:
    siodi: siodi
    data: "./data/"                 # not used yet
    DATA_STORE_PATH: "./data/"             # all CAN-data files from CAN-Store.py
    CONFIG_PATH: "./"                  # path for CAN-dbc and associated yml
    log: "./log/"

suffixes:
    log: # "-%Y_%m_%d__%H-%M-%S"     #date and time
         "-%Y_%m_%d"                #date only
         #""                         # hostname only
    data: "-%Y_%m_%d__%H-%M-%S"     #date and time
          #"-%Y_%m_%d"               #date only
          #""                        #without date and time

debug:
    #datefmt: "%d.%m.%Y %H:%M:%S"      # normal
    datefmt: "%d.%m.%Y %H:%M:%S.%s"   # fine (with ms)
    hirestime: False                    # time resolution in data logs (true=ms, false=s)
    logYML: False                      #put the yml-file into the log
    verbose: True
    withRFID: True

